engine/src/main/battlecode/server/Server.java, engine/src/main/battlecode/world/GameWorld.java, engine/src/main/battlecode/world/InternalRobot.java, engine/src/main/battlecode/world/RobotControllerImpl.java
Removes incorrectly sent change influence actions, adds logic for processing neutral enlightenment centers.
=> Engine patch

frontend/src/views/home.js
=> Fix GitHub link still pointing to Battlehack repository

backend/api/views.py
was previously commented out, never noticed -- oops
=> Re-enable pub to pubsub

frontend/src/views/getting-started.js, frontend/src/views/issues.js
hah this was not supposed to be weebinfra
Adapting installation instructions from bc20, makes some links more visible
=> Webinfra website content

frontend/src/views/scrimmaging.js
this_url actually did cause problems (that i don't fully understand); here's a quick fix
=> Fix scrimmage visualizer link

client/visualizer/src/config.ts, client/visualizer/src/main/sidebar.ts, client/visualizer/src/mapeditor/action/generator.ts, client/visualizer/src/mapeditor/form.ts, client/visualizer/src/mapeditor/forms/robots.ts, client/visualizer/src/mapeditor/forms/symmetry.ts, client/visualizer/src/mapeditor/mapeditor.ts, gradle.properties, specs/specs.md.html
- New color scheme / terraformed Mars
- Revamped map editor
- Performance improvements
Most of the changes are already on master, sorry! Mostly looking for feedback on the new color scheme.
=> Client update

backend/api/views.py, frontend/src/api.js, frontend/src/components/paginationControl.js, frontend/src/views/scrimmaging.js
#49 
adds basic pagination for faster load time, now ~6 seconds 
todo: optimize time for the scrimmage requests
=> Scrimmage pagination

frontend/src/api.js, frontend/src/views/countdown.js, frontend/src/views/submissions.js, frontend/src/views/tournaments.js
Update tour info: we now have 2 sprint tours! Also update the format info (to match battlecode, not battlehack).
Update the submission timer, too.
=> Webinfra update tour info

client/visualizer/src/config.ts, gradle.properties, specs/specs.md.html
=> changelog, version numbers

frontend/src/api.js
account for changing response format, with pagination being a thing
=> Fix joining team

frontend/src/views/submissions.js
=> Add more helpful submission info

infrastructure/compile.Dockerfile, infrastructure/game.Dockerfile, infrastructure/scrimmage.Dockerfile, infrastructure/tournament.Dockerfile
Now Jerry can't make fun of my crlf line endings
Changes the commands docker runs to avoid needing the shebang
=> changed  docker commands

frontend/src/api.js, frontend/src/views/submissions.js, frontend/src/views/tournaments.js
just updates tour deadline for sprint 2 and includes winner on tour page
resolve #294
=> Update tour info

backend/api/views.py
=> Add backend endpoint to requeue scrimmages

backend/README.md, backend/api/models.py, backend/docs/ELIGIBILITY.md, frontend/deploy.sh, frontend/src/views/team.js
I don't have a proper frontend staging environment set up, could you check that this functions correctly as intended? Looks like all the code was already there and just needed to be uncommented.
=> Fix eligibility options, resolve #314

frontend/src/components/rankingTeamList.js
Show some icons for eligibility classes.
=> Show eligibility icons

client/visualizer/src/sidebar/stats.ts
oops
hopefully merged before finals (and maybe intl quals?) to get those tasty income graphs
=> fix bug with income graph not displaying for new matches

frontend/src/api.js, frontend/src/views/submissions.js, frontend/src/views/tournaments.js
(also addresses some out-of-date writing)
=> Bump eligibility for hs and newbie tours

frontend/src/api.js, frontend/src/views/submissions.js, frontend/src/views/team.js, frontend/src/views/tournaments.js
hs tour is eligible to only US students. Jerry and I figured to change the name too, to be more clear
=> Change HS tour to US HS tour

backend/api/serializers.py, frontend/src/views/account.js
we didn't save in backend -- done now
Also a few other changes to frontend for clarity too
=> Make user email editable

frontend/src/views/tournaments.js
I'm not a frontend person and feel proud that I was able to get `pre` to work… if you absolutely detest it then feel free to update to a table.
If it looks good then please deploy if you get a chance! :))
=> Add results

.gitignore, backend/resumes/download.py, backend/resumes/notes.txt, backend/resumes/sql.txt
resume-downloading scripts from 2020. repo Also improvements to script, documentation etc
=> Add resume code
